version: '3'

services:
  frontend:
    build:
      context: ./wdslab_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./wdslab_frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./wdslab_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./wdslab_backend:/app
    environment:
      - DEBUG=True
      - DB_HOST=db  
    depends_on:
      - db

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0312
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: