version: '3'

services:
  frontend:
    build:
      context: ./wdslab_frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./wdslab_frontend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./wdslab_backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./wdslab_backend:/app
    environment:
      - DEBUG=True
      - DB_HOST=db  
      - DB_PASSWORD=0312 # 이 줄 추가
    depends_on:
      db:
        condition: service_healthy
    command: >
      bash -c "
        echo 'Waiting for PostgreSQL to be ready...'
        while !</dev/tcp/db/5432; do sleep 1; done
        echo 'PostgreSQL is ready!'
        python manage.py migrate
        python manage.py runserver 0.0.0.0:8000
      "

  db:
    image: postgres:14
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=wds
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0312
    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: